version: '3'
services:
  backend1:
    image: nginx:latest
    container_name: 'backend1'
    restart: always
    volumes:
      - ./backend1:/usr/share/nginx/html
    ports:
      - 7001:80
    #networks:
    #  node_net:
    #    ipv4_address: 192.168.1.1

  backend2:
    image: nginx:latest
    container_name: 'backend2'
    restart: always
    volumes:
      - ./backend2:/usr/share/nginx/html
    ports:
      - 7002:80
    #networks:
    #  node_net:
    #    ipv4_address: 192.168.1.2

  frontend_loadbalancer:
    image: nginx:latest
    container_name: 'frontend_loadbalancer'
    restart: always
    volumes:
      - ./frontend_loadbalancer/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    #networks:
    #  node_net:
    #    ipv4_address: 192.168.1.10

#networks:
#  node_net:
#    name: node_net
#    ipam:
#      config:
#        - subnet: 192.168.1.0/24

