version: '3.4'

services:
  NodeA:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_node
    restart: always
    container_name: node_a
    networks:
      node_net:
        ipv4_address: 192.168.1.2

  NodeB:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_node
    restart: always
    container_name: node_b
    networks:
      node_net:
        ipv4_address: 192.168.1.3

  NodeC:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_node
    restart: always
    container_name: node_c
    networks:
      node_net:
        ipv4_address: 192.168.1.4

networks:
  node_net:
    name: node_net
    ipam:
      config:
        - subnet: 192.168.1.0/24
