version: '3.4'

services:
  NodeA:
    image: ubuntu:20.04
    hostname: node_a
    container_name: node_a
    restart: always
    networks:
      node_AB_net:
        ipv4_address: 192.168.1.2

  NodeB:
    image: ubuntu:20.04
    hostname: node_b
    container_name: node_b
    restart: always
    networks:
      node_AB_net:
        ipv4_address: 192.168.1.3
      node_BC_net:
        ipv4_address: 192.168.2.2

  NodeC:
    image: ubuntu:20.04
    hostname: node_c
    container_name: node_c
    restart: always
    networks:
      node_BC_net:
        ipv4_address: 192.168.2.3

networks:
  node_AB_net:
    name: node_AB_net
    ipam:
      config:
        - subnet: 192.168.1.0/24
  node_BC_net:
    name: node_BC_net
    ipam:
      config:
        - subnet: 192.168.2.0/24